version: '3'

services:
  app:
    build: .
    command: yarn dev
    working_dir: /home/node/app
    restart: always
    tty: true
    networks:
      - mysql
    depends_on:
      - mysql
    ports:
      - '3333:3333'
    volumes:
      - '.:/home/node/app'
      - /home/node/app/node_modules

  mysql:
    image: mysql:5.7
    restart: always
    volumes:
      - './tmp/mysql:/var/lib/mysql'
    networks:
      - mysql
    ports:
      - '3306:3306'
    environment:
      - MYSQL_PASSWORD=root
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=development

networks:
  mysql:
