version: '3'

services:
  app:
    build: .
    restart: always
    tty: true
    networks:
      - redis
      - postgres
    depends_on:
      - redis
      - postgres
    ports:
      - '3333:3333'
    volumes:
      - .:/home/node/app
      - /home/node/app/node_modules

  postgres:
    image: postgres:alpine
    restart: always
    volumes:
      - ./tmp/postgres:/var/lib/postgresql/data
    networks:
      - postgres
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_DB=dbname
      - POSTGRES_USER=dbuser
      - POSTGRES_PASSWORD=dbpasswd

  redis:
    image: redis:alpine
    command: redis-server --appendonly yes
    volumes:
      - ./tmp/redis:/data
    networks:
      - redis
    ports:
      - '6379:6379'

networks:
  postgres:
  redis:
